### ISSUE TITLE
Heading in Arduino is not correct before/and after calibration

### ISSUE THREAD

**Issue by vbahtev** [ozzmaker/BerryIMU#14]
I use use **GPS-IMU V2** and when compile and run code from repository for heading i do not receive a real values.
Values that receive from sensors are before and after calibration (use calibration code from git) are  [from ~30 to ~200]  for 0-360 degree rotation.

Anybody with some solution for that ?

**Comment by mwilliams03** [comment]
please contact sales@ozzmaker.com

**Comment by vbahtev** [comment]
using this https://gist.github.com/vbahtev/b05f1895776cec5828db6746d5ba9a11 after 360 degree rotation, can receive correct values from heading.
