### ISSUE TITLE
Z Axis of accelero

### ISSUE THREAD

**Issue by alfandinorasyid** [ozzmaker/BerryIMU#16]
How do we know the AccZangle and the Kalman of Z axis?

**Comment by mwilliams03** [comment]
The Gyro and Accelerometer cannot be used to get Z axis as the Z axis doesn't change do to gravity.
What you are after is "yaw".  The magnetometer used to get this reading.  What you need is AHRS (attitude and heading reference system) code. There is plenty of AHRS code on the internet that works with the LSM9DS1. Google "LMS9DS1 AHRS"

**Comment by mwilliams03** [comment]
Not an issue with this code
