### ISSUE TITLE
missing BerryIMUv4 Schematic under hardware

### ISSUE THREAD

**Issue by vovacooper** [ozzmaker/BerryIMU#20]

**Comment by peterp-ozzmaker** [comment]
There is no V4 of the BerryIMU, on V2 or V3

**Comment by vovacooper** [comment]
trying to understand why the GPS doesn't work via I2C

**Comment by mwilliams03** [comment]
To make the information more accessible, I have added the schematic to the product page and quick start guide
[quick start guide](https://ozzmaker.com/berrygps-berrygps-imu-quick-start-guide/)
