### ISSUE TITLE
Wrong register assignment in LSM6DSL.py

### ISSUE THREAD

**Issue by pkstrsk** [ozzmaker/BerryIMU#23]
I believe the register address assigned in LSM6DSL.py (at least the one in the SPI example) on line 7. It assignes the same register address as line 6. Those being control registers, it renders any settings in-code incorrect, such as ODR.. The correct address for CTRL1_XL is 0x10, as in the file, but for CTRL8_XL it should be 0x17.

**Comment by peterp-ozzmaker** [comment]
Wow!! well spotted! it has been fixed
